In [5]:
# !pip install tensorflow
# !pip install pydot
# !conda install graphviz

     |████████████████████████████████| 207.1 MB 61.8 MB/s eta 0:00:01
     |████████████████████████████████| 4.2 MB 577 kB/s eta 0:00:01
     |████████████████████████████████| 126 kB 22.6 MB/s eta 0:00:01
     |████████████████████████████████| 42 kB 4.3 MB/s  eta 0:00:01
     |████████████████████████████████| 12.2 MB 27.7 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 8.0 MB/s  eta 0:00:01
     |████████████████████████████████| 3.1 MB 2.1 MB/s eta 0:00:01
     |████████████████████████████████| 65 kB 9.7 MB/s  eta 0:00:01
     |████████████████████████████████| 463 kB 23.5 MB/s eta 0:00:01
     |████████████████████████████████| 1.0 MB 18.2 MB/s eta 0:00:01
     |████████████████████████████████| 1.6 MB 2.8 MB/s eta 0:00:01
     |████████████████████████████████| 1.3 MB 22.5 MB/s eta 0:00:01
     |████████████████████████████████| 5.8 MB 24.1 MB/s eta 0:00:01
     |████████████████████████████████| 155 kB 33.0 MB/s eta 0:00:01
     |███████████████████████████████

In [11]:
import tensorflow as tf
import numpy as np
print(tensorflow.__version__)

2.7.0


In [12]:
#--- print additional output about computations
tf.debugging.set_log_device_placement(True)

In [13]:
#--- are we executing eagerly?
tf.executing_eagerly() 

True

### Constants

In [14]:
x0 = tf.constant(3)
x0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [15]:
x0.shape

TensorShape([])

In [16]:
x0.dtype

tf.int32

In [17]:
x0.numpy()

3

In [18]:
result0 = x0+5
result0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [19]:
x1 = tf.constant([1.1,2.2,3.3,4.4])
x1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [20]:
result1 = x1+5
result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [22]:
result1 = tf.add(x1, tf.constant(5.0))
result1 #--tensors are immutable

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [25]:
x2 = tf.constant([[1,2,3,4],[5,6,7,8]])
x2 = tf.cast(x2,tf.float32)
x2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [26]:
result3 = tf.multiply(x1,x2) #---elementwise multiplication
result3

Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [28]:
arr_x1 = x1.numpy()
arr_x1 

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [29]:
arr_4 = np.array([[10,20],[30,40],[50,60]])
arr_4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [32]:
x4 = tf.convert_to_tensor(arr_4)
x4

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [33]:
np.square(x2) #-- square every element of the array

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]], dtype=float32)

In [34]:
np.sqrt(x2)

array([[1.       , 1.4142135, 1.7320508, 2.       ],
       [2.236068 , 2.4494898, 2.6457512, 2.828427 ]], dtype=float32)

In [35]:
tf.is_tensor(arr_4)

False

In [39]:
t0 = tf.zeros([3,5],tf.int32)
t0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [40]:
t0_reshaped = tf.reshape(t0,(5,3))
t0_reshaped

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
#--variables are mutable

In [46]:
v1 = tf.Variable([[1.5,2,5],[2,6,8]], dtype = tf.float32)
v1
v2 = tf.Variable([[1,2,3],[4,5,6]], dtype = tf.float32)
v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [47]:
tf.add(v1,v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5,  4. ,  8. ],
       [ 6. , 11. , 14. ]], dtype=float32)>

In [48]:
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [50]:
v1.numpy()

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)

In [ ]:
#---tensors are not mutable, but variables are

In [51]:
v1.assign([[10,20,30],[40,50,60]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [52]:
v1[0,0].assign(100)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ResourceStridedSliceAssign in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [53]:
v1.assign_add([[1,1,1],[1,1,1]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[101.,  21.,  31.],
       [ 41.,  51.,  61.]], dtype=float32)>

In [54]:
v1.assign_sub([[1,1,1],[1,1,1]])

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [ ]:
#---variables do not share memory