In [1]:
import tensorflow as tf

In [2]:
#--- are we executing eagerly?
tf.executing_eagerly() 

True

In [4]:
x = [[10.]]
res = tf.matmul(x,x) #--matrix multiplication

In [5]:
res

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[100.]], dtype=float32)>

In [6]:
a = tf.constant([[10,20], [30,40]])
b = tf.add(a,2)
print(b)

tf.Tensor(
[[12 22]
 [32 42]], shape=(2, 2), dtype=int32)


In [11]:
print( a*b) #--element wise multiplication

tf.Tensor(
[[ 120  440]
 [ 960 1680]], shape=(2, 2), dtype=int32)


In [13]:
m  = tf.Variable([4,5,6], dtype = tf.float32, name = 'm')
c  = tf.Variable([1,1,1], dtype = tf.float32, name = 'c')

In [14]:
x = tf.Variable([100.,100.,100.], tf.float32, name = 'x')

In [15]:
y = m*x+c

In [16]:
y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([401., 501., 601.], dtype=float32)>